# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /var/lib/snapd/snap/clion/193/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /var/lib/snapd/snap/clion/193/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cringevictim/Projects/AP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cringevictim/Projects/AP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/var/lib/snapd/snap/clion/193/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cringevictim/Projects/AP/CMakeFiles /home/cringevictim/Projects/AP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cringevictim/Projects/AP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 11

# Build rule for target.
11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 11
.PHONY : 11

# fast build rule for target.
11/fast:
	$(MAKE) $(MAKESILENT) -f 11/CMakeFiles/11.dir/build.make 11/CMakeFiles/11.dir/build
.PHONY : 11/fast

#=============================================================================
# Target rules for targets named 12

# Build rule for target.
12: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 12
.PHONY : 12

# fast build rule for target.
12/fast:
	$(MAKE) $(MAKESILENT) -f 12/CMakeFiles/12.dir/build.make 12/CMakeFiles/12.dir/build
.PHONY : 12/fast

#=============================================================================
# Target rules for targets named 13

# Build rule for target.
13: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 13
.PHONY : 13

# fast build rule for target.
13/fast:
	$(MAKE) $(MAKESILENT) -f 13/CMakeFiles/13.dir/build.make 13/CMakeFiles/13.dir/build
.PHONY : 13/fast

#=============================================================================
# Target rules for targets named 14

# Build rule for target.
14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 14
.PHONY : 14

# fast build rule for target.
14/fast:
	$(MAKE) $(MAKESILENT) -f 14/CMakeFiles/14.dir/build.make 14/CMakeFiles/14.dir/build
.PHONY : 14/fast

#=============================================================================
# Target rules for targets named 15

# Build rule for target.
15: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 15
.PHONY : 15

# fast build rule for target.
15/fast:
	$(MAKE) $(MAKESILENT) -f 15/CMakeFiles/15.dir/build.make 15/CMakeFiles/15.dir/build
.PHONY : 15/fast

#=============================================================================
# Target rules for targets named 16

# Build rule for target.
16: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 16
.PHONY : 16

# fast build rule for target.
16/fast:
	$(MAKE) $(MAKESILENT) -f 16/CMakeFiles/16.dir/build.make 16/CMakeFiles/16.dir/build
.PHONY : 16/fast

#=============================================================================
# Target rules for targets named 17

# Build rule for target.
17: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 17
.PHONY : 17

# fast build rule for target.
17/fast:
	$(MAKE) $(MAKESILENT) -f 17/CMakeFiles/17.dir/build.make 17/CMakeFiles/17.dir/build
.PHONY : 17/fast

#=============================================================================
# Target rules for targets named KP2

# Build rule for target.
KP2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KP2
.PHONY : KP2

# fast build rule for target.
KP2/fast:
	$(MAKE) $(MAKESILENT) -f KP2/CMakeFiles/KP2.dir/build.make KP2/CMakeFiles/KP2.dir/build
.PHONY : KP2/fast

#=============================================================================
# Target rules for targets named Kursach

# Build rule for target.
Kursach: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Kursach
.PHONY : Kursach

# fast build rule for target.
Kursach/fast:
	$(MAKE) $(MAKESILENT) -f Kursach/CMakeFiles/Kursach.dir/build.make Kursach/CMakeFiles/Kursach.dir/build
.PHONY : Kursach/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 11"
	@echo "... 12"
	@echo "... 13"
	@echo "... 14"
	@echo "... 15"
	@echo "... 16"
	@echo "... 17"
	@echo "... KP2"
	@echo "... Kursach"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

